package pl.dietadvisor.common.shoppingList.model.dynamodb;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConverted;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import pl.dietadvisor.common.shared.util.converter.dynamodb.LocalDateTimeConverter;
import pl.dietadvisor.common.shoppingList.enums.ShoppingListSource;
import pl.dietadvisor.common.shoppingList.util.converter.dynamodb.ShoppingListSourceConverter;

import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.Map;

@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "shopping-lists")
public class ShoppingList implements Serializable {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;
    @DynamoDBTypeConverted(converter = ShoppingListSourceConverter.class)
    private ShoppingListSource source;
    private Map<String, BigDecimal> productIdsToQuantities;
    @DynamoDBTypeConverted(converter = LocalDateTimeConverter.class)
    private LocalDateTime createdAt;
}
