package pl.dietadvisor.common.recipeScraper.model.dynamodb;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConverted;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import pl.dietadvisor.common.recipeScraper.enums.RecipeScrapeJobSource;
import pl.dietadvisor.common.recipeScraper.enums.RecipeScrapeJobState;
import pl.dietadvisor.common.recipeScraper.util.converter.dynamodb.RecipeScrapeJobSourceConverter;
import pl.dietadvisor.common.recipeScraper.util.converter.dynamodb.RecipeScrapeJobStateConverter;
import pl.dietadvisor.common.shared.util.converter.dynamodb.LocalDateTimeConverter;

import java.time.LocalDateTime;

@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "recipe-scrape-jobs")
public class RecipeScrapeJob {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;
    @DynamoDBTypeConverted(converter = RecipeScrapeJobStateConverter.class)
    private RecipeScrapeJobState state;
    @DynamoDBTypeConverted(converter = RecipeScrapeJobSourceConverter.class)
    private RecipeScrapeJobSource source;
    private String errorMessage;
    private Integer scrapedRecipesNumber;
    @DynamoDBTypeConverted(converter = LocalDateTimeConverter.class)
    private LocalDateTime createdAt;
    @DynamoDBTypeConverted(converter = LocalDateTimeConverter.class)
    private LocalDateTime updatedAt;
}