package pl.dietadvisor.common.productScraper.model.dynamodb;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConverted;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import pl.dietadvisor.common.productScraper.enums.ProductScrapeJobSource;
import pl.dietadvisor.common.productScraper.enums.ProductScrapeJobState;
import pl.dietadvisor.common.shared.util.converter.dynamodb.LocalDateTimeConverter;
import pl.dietadvisor.common.productScraper.util.converter.dynamodb.ProductScrapeJobSourceConverter;
import pl.dietadvisor.common.productScraper.util.converter.dynamodb.ProductScrapeJobStateConverter;

import java.time.LocalDateTime;

@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "product-scrape-jobs")
public class ProductScrapeJob {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;
    @DynamoDBTypeConverted(converter = ProductScrapeJobStateConverter.class)
    private ProductScrapeJobState state;
    @DynamoDBTypeConverted(converter = ProductScrapeJobSourceConverter.class)
    private ProductScrapeJobSource source;
    private String errorMessage;
    private Integer scrapedProductsNumber;
    @DynamoDBTypeConverted(converter = LocalDateTimeConverter.class)
    private LocalDateTime createdAt;
    @DynamoDBTypeConverted(converter = LocalDateTimeConverter.class)
    private LocalDateTime updatedAt;
}
