package pl.dietadvisor.common.recipe.model.dynamodb;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConverted;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import pl.dietadvisor.common.shared.util.converter.dynamodb.LocalDateTimeConverter;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Map;

@Data
@Builder(toBuilder = true)
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "recipe-scrape-logs")
public class RecipeScrapeLog {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;
    private String jobId;
    private List<Integer> mealNumbers;
    private String name;
    //TODO: adres fotki do s3 lub lokalnie do foleru
    private Map<String, BigDecimal> productsNamesToQuantities;
    private String recipe;
    @DynamoDBTypeConverted(converter = LocalDateTimeConverter.class)
    private LocalDateTime createdAt;
}
